### ISSUE TITLE
Persist sseraphini.cc score

### ISSUE THREAD

**Issue by Nick-Gabe** [sibelius/ccsseraphini#1224]
# Feature Request
Persist sseraphini score

## Why it is needed
Since the score only picks the 100 most recent tweets, if the user tweets too frequently, their score will disappear fast.
Therefore benefiting who doesn't tweet so often but uses cc frequently than someone who sometimes uses cc but does a lot of tweets

## Possible implementation
When someone goes to the score page of a user, save their score in a database along with the tweet ids that have been already counted, and when someone goes to the page again, increment the score based on the score of the tweets that weren't already counted, and redo this proccess for every visit.

I know this isn't ideal since it would only update "manually" when you go to the page, so any other implementation idea or improvement would be very much welcome.

**Comment by pjonatansr** [comment]
Today, we already save the tweets in a mongodb and the score is updated daily.

## Suggestion

To implement this score on sseraphini.cc, I suggest:

- Creating a lambda to query all RankedTweets for an author_id.
- Sum score and public metrics for each tweet.

## How the score update works

Every time the cc @sseraphini is marked, twitter sends tweet data via stream to the bot, which in turn processes the tweet and updates a temporary collection in mongodb. This collection is called TemporaryTweet. Therefore, the bot periodically looks at this collection, queries twitter to obtain the most recent tweet data and persists these data in another collection called RankedTweet.

### TemporaryTweets

Tweets are saved in the TemporaryTweet collection, which is a temporary collection, that is, it is deleted every 24 hours. This collection is used to mark the tweets that we will consider for the creation of a ranking.

The schema of temporary tweets is very simple, it only saves the tweet id and the date it was created, see:

```
{
  tweet_id: {
    type: String,
    required: true,
  },
  created_at: {
    type: Date,
    required: true,
  },
}
```

### RankedTweets

The RankedTweet collection is the collection that stores the tweets that will be used to create the ranking. This collection is updated every 24 hours, whenever a daily, weekly, biweekly or monthly ranking is generated, and also when the scheduler of tweets synchronization runs.

The schema of ranked tweets is more complete. See:

```
{
  tweet_id: {
    type: String,
    required: true,
  },
  created_at: {
    type: Date,
    required: true,
  },
  author_id: {
    type: String,
    required: true,
  },
  public_metrics: {
    type: {
      retweet_count: Number,
      reply_count: Number,
      like_count: Number,
      quote_count: Number,
    },
    required: true,
  },
  score: {
    type: Number,
    required: true,
  },
  last_updated: Date,
  changes_since_last_update: Boolean,
}
```

- The `tweet_id` field is the tweet id.
- The `created_at` field is the date the tweet was created.
- **The `author_id` field is the id of the tweet author.**
- **The `public_metrics` field is an object that stores the tweet metrics, such as retweets, replies, likes and quotes.**
- **The `score` field is the tweet score, which is calculated from the tweet metrics.**
- The `last_updated` field is the date the tweet was last updated.
- The `changes_since_last_update` field is a boolean that indicates whether the tweet has been changed since the last update.

**Comment by pjonatansr** [comment]
Done 
![image](https://user-images.githubusercontent.com/5343791/207054028-4361b264-05a2-4d6f-8d86-3cad0261d8cc.png)

**Comment by Nick-Gabe** [comment]
perfect! tysm @pjonatansr
